---

on:
  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: container:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Start test container
        run: docker run --name test-container -d --cgroupns=host --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw container:ci
      
      - name: Verify Ansible is present
        run: docker exec --tty test-container env TERM=xterm ansible --version
